### ISSUE TITLE
feat: Remove @react-native-async-storage/async-storage dependency

### ISSUE THREAD

**Issue by 509dave16** [segmentio/sovran-react-native#29]
This `@react-native-async-storage/async-storage` dependency is hard coded. I know that `AsyncStorage` API from `react-native` is deprecated. But if `sovran-react-native` could transition away from using `@react-native-async-storage/async-storage` then that would be one less dependency to install. Especially if a user/client is using a different store persistor that is not based on `@react-native-async-storage/async-storage`(e.g. MMKV): https://github.com/segmentio/analytics-react-native/pull/549

I know there may have been reasons for transitioning away from `react-native`'s api `AsyncStorage`. If going back to that would break functionality in some scenarios, then maybe we could either:
1. Have default be an "in-memory" persistor like in this unit test here: https://github.com/segmentio/analytics-react-native/blob/1f960f04cc53fd8c3dbe07aa9edd05aa7cf388d9/packages/core/src/storage/__tests__/sovranStorage.test.ts#L109-L117
2. Or make `createStore`'s argument `config` of type `StorageConfig` be required as well as the `persist` sub-property of type `PersistenceConfig` and it's sub-property `persistor`. And then document how to use `@react-native-async-storage/async-storage` as a dependency. Could also document on how to use MMKV.

**Comment by gabrieldonadel** [comment]
@oscb @alanjcharles would you accept a PR adding the support for different storage providers instead of relying on `@react-native-async-storage/async-storage`? Something like https://github.com/apollographql/apollo-cache-persist/blob/master/docs/storage-providers.md.

If so I can open a PR adding this functionality.

**Comment by georgeilas-tem** [comment]
Hi,

We used the option ``storePersistor`` and created a custom MMKV persistor for ``segmentio/analytics-react-native``, so theoretically sovran doesn't even use async storage anymore. But we can't delete the ``@react-native-async-storage/async-storage`` package from our project because it's hardcoded. It's a bit messy and inefficient to keep a package in the bundle that we don't use at all. 

You mentioned a in-memory default persistor: https://github.com/segmentio/sovran-react-native/issues/29. Any news on this?

**Comment by georgeilas-tem** [comment]
Is this project maintained anymore?

**Comment by isaachinman** [comment]
To expand on @georgeilas-tem's solution, an MMKV store persistor can be written like:

```tsx
const segmentMMKV = new MMKV()

export const segmentClient = createClient({
  storePersistor: {
    get: async <T>(key: string) => segmentMMKV.getString(key) as T,
    set: async <T>(key: string, state: T) =>
      segmentMMKV.set(key, JSON.stringify(state)),
  },
  trackAppLifecycleEvents: true,
  writeKey: config.segment.writeKey,
})
```

However, as @georgeilas-tem mentioned, we still need to keep `@react-native-async-storage/async-storage@1.17.10` in our bundle, or else we hit `NativeModule: AsyncStorage is null` errors, despite not actually needing the package at all.

I see that this package hasn't been touched in 10 months, yet is still a mandatory requirement for `@segment/analytics-react-native`, which is actively maintained.

@oscb @alanjcharles Can you please provide a response on this issue?

**Comment by oscb** [comment]
This change was just merged: https://github.com/segmentio/analytics-react-native/pull/779

This repository will be archived now. We migrated this into the `analytics-react-native` monorepo.
